-   id: oxfmt
    name: oxfmt
    description: 'Formatter for the JavaScript Oxidation Compiler'
    entry: oxfmt --no-error-on-unmatched-pattern
    language: node
    types: [text]
    args: []
    require_serial: false
    additional_dependencies: ["oxfmt@0.57.0"]
    minimum_pre_commit_version: '2.9.2'
